apiVersion: v1
items:
- apiVersion: v1
  data:
    postgres-password: Q3FrWThJZHFFYw==
  kind: Secret
  metadata:
    creationTimestamp: null
    labels:
      app: postgresql
      chart: postgresql-0.15.0
      heritage: Tiller
      release: kds
    name: kds-postgresql
  type: Opaque
- apiVersion: v1
  kind: ConfigMap
  metadata:
    creationTimestamp: null
    labels:
      app: postgresql
      chart: postgresql-0.15.0
      heritage: Tiller
      release: kds
    name: kds-postgresql
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      app: postgresql
      chart: postgresql-0.15.0
      heritage: Tiller
      release: kds
    name: kds-postgresql
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 8Gi
    volumeMode: Filesystem
  status:
    phase: Pending
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app: postgresql
      chart: postgresql-0.15.0
      heritage: Tiller
      release: kds
    name: kds-postgresql
  spec:
    ports:
    - name: postgresql
      port: 5432
      protocol: TCP
      targetPort: postgresql
    selector:
      app: postgresql
      release: kds
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    creationTimestamp: null
    labels:
      app: postgresql
      chart: postgresql-0.15.0
      heritage: Tiller
      release: kds
    name: kds-postgresql
  spec:
    progressDeadlineSeconds: 2147483647
    replicas: 1
    revisionHistoryLimit: 2147483647
    selector:
      matchLabels:
        app: postgresql
        release: kds
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: postgresql
          release: kds
      spec:
        containers:
        - env:
          - name: POSTGRES_USER
            value: postgres
          - name: PGUSER
            value: postgres
          - name: POSTGRES_DB
            value: users
          - name: POSTGRES_INITDB_ARGS
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                key: postgres-password
                name: kds-postgresql
          - name: POD_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          image: postgres:9.6.2
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
              - sh
              - -c
              - exec pg_isready --host $POD_IP
            failureThreshold: 6
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          name: kds-postgresql
          ports:
          - containerPort: 5432
            name: postgresql
            protocol: TCP
          readinessProbe:
            exec:
              command:
              - sh
              - -c
              - exec pg_isready --host $POD_IP
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 3
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /var/lib/postgresql/data/pgdata
            name: data
            subPath: postgresql-db
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: data
          persistentVolumeClaim:
            claimName: kds-postgresql
  status: {}
kind: List
metadata: {}
